forums/urls.py
from django.conf.urls import *

from forums.views import Discussions, User,Errors

app_name = "forums"

urlpatterns = [
	url(r'^(?P<sort>(|featured|latest|unanswered))$' , Discussions.Index.as_view() , name = "index"), #for discussions index
	url(r'^ask$' , Discussions.PostView.as_view() , name="ask_question"), #for posting new question
	url(r'^vote$',Discussions.QuestionView.as_view() , name="vote"), #for voting a question
	url(r'^comment$' , Discussions.CommentView.as_view(),name="comment" , kwargs = {"method" : "question"}), #For Commenting on a question
	url(r'^comment/reply$' , Discussions.CommentView.as_view() , kwargs = {"method" : "comment"}), #For replying on a comment
	url(r'^comment/vote$' , Discussions.CommentView.as_view() , kwargs = {"action" : "vote"}), #For voting on a comment
	url(r'^comment/favourite$' , User.ProfileView.as_view() , kwargs = {"action" : "favourite" , "method" : "comment"}), #For Adding a favourite
	url(r'^post/favourite$' , User.ProfileView.as_view() , kwargs = {"action" : "favourite" , "method" : "question"}), #For Adding a favourite
	url(r'^message$',User.AccountView.as_view()), #For sending a message
	url(r'^(?P<key>.+)$' , Discussions.Thread.as_view() , name = "thread"), #For visiting a thread
]

neuron/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from forums.views.User import ProfileView,AccountView
from forums.views.Discussions import Index,Redirect

urlpatterns = [
    url(r'^$',Redirect.as_view()),  
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/profile[/]$' , ProfileView.as_view() , name="profile"),
    url(r'^accounts/',include("allauth.urls")),
    url(r'^discussions/' , include("forums.urls")),
    url(r'^user/(?P<username>.+)$',AccountView.as_view() , name= "account")
]

forums/models.py
import re
from django.db import models
from django.contrib.auth.models import User
from mongoengine import *
from forums.Algorithms import voteCount , hot , confidence
import json , datetime

class _BaseForUser():
	'''
	
	'''
	@property
	def user(self):
		'''Returns the user which posted the Post/Comment'''
		return User.objects.get(pk = self.user_id)

	@user.setter
	def user(self,user):
		'''
		Simple way to set user.
		Instead of Model.user_id = request.user.id we can do Model.user = request.user	
		'''
		self.user_id = user.id

class Base(_BaseForUser):
	'''Base Class from which wraps some basic functionality associated with Questions and Comments'''

	parent = None #Helper Attribute 
	'''
	Following methods have been wrapped in @classmethods so that some operations can be encapsulated in the Model
	'''

	@classmethod
	def featured(self , page = 1):
		'''
		Returns Featured Posts/Comments. Sorted by Descending score
		Pagination achieved through array slicing
		'''
		first = (page-1)*10 + 1
		last = page*10
		return self.objects.order_by("-score")[first:last]
	
	@classmethod
	def latest(self , page = 1):
		'''Returns Latest Posts/Comments. Latest post/comment first'''
		first = (page-1)*10 + 1
		last = page*10
		return self.objects.order_by("-pub_date")[first:last]
	
	@classmethod
	def unanswered(self , page = 1):
		'''Returns Posts/Comments with zero comments'''
		first = (page-1)*10 + 1
		last = page*10		
		return self.objects.filter(comments__size = 0)[first:last]
	
	@classmethod
	def getById(self,pk):
		'''Quick Lookup using the primary key'''
		return self.objects.get(id = pk)

	@classmethod
	def setVote(self,qid,vote):
		'''Adds a vote to the Model instance'''
		q = self.getById(qid)
		q._vote(vote)
		return q

	@property
	def voteCount(self):
		'''Iterates through the votes and adds each vote'''
		return sum([int(e.vote) for e in self.votes])

	@classmethod
	def setComment(self,qid,comment,uid):
		'''
		Add a comment to a post
		Add a reply to a comment
		'''
		q = self.getById(qid)
		c = self.comment(comment_text = comment , pub_date = datetime.datetime.now())
		if self.comment.parent is not None:
			setattr(c,self.comment.parent,q)
		q.addComment(c)
		return c

	def addComment(self,comment):
		'''
		Method to add comment if direct instance of comment is available
		'''
		if isinstance(comment,self.comment):
			comment.save()
			print("adding Comment")
			self.comments.append(comment)
			self.save()
		else:
			raise TypeError

	def calcScore(self):
		'''
		Method to calculate Score for featured posts. Default implementation is for Questions/Posts
		'''
		self.score = hot(self.voteCount , self.pub_date)
		self.save()

	def _vote(self,vote):
		'''
		Internal implementation for vote setting
		'''
		try:
			past = self.votes.get(user_id = vote.get("uid"))
		except Exception as e:
			past = self.votes.create(user_id = vote.get("uid"))
		past.vote = int(vote.get("vote"))
		past.pub_date = datetime.datetime.now()
		self.save()
		if self.scorable:
			self.calcScore()
		return self

class Vote(EmbeddedDocument):
	'''
	Model for Votes
	'''
	user_id = IntField(default = 1)
	vote = IntField(default = 0)

class CommentReplies(Document,_BaseForUser):
	'''
	Model for Comment Replies
	'''
	parent = "comment"
	comment_text = StringField(max_length = 1000)
	user_id = IntField(default = 1)
	pub_date = DateTimeField(help_text = "date published")
	comment = ReferenceField("Comment")

class Comment(Base,Document):
	'''
	Model for Comments
	'''
	scorable = True #Helper attribute which decides whether score should be calculated if this model is voted. calcScore() method should be defined if set to True


	comment = CommentReplies
	parent = "question_id"
	comment_text = StringField(max_length = 100)
	votes = EmbeddedDocumentListField(Vote)
	user_id = IntField(default = 1)
	pub_date = DateTimeField(help_text = "date published")
	question_id = ReferenceField("Question")
	comments = ListField(ReferenceField(CommentReplies))
	score = FloatField(default = 0)

	def calcScore(self):
		self.score = confidence(len([e for e in self.votes if e.vote == 1]) , len([e for e in self.votes if e.vote == -1]))
		self.save()

class Question(Base,Document):
	'''Model for Comments'''
	comment = Comment
	scorable = True

	question = StringField(max_length = 200)
	description = StringField(max_length = 1000)
	pub_date = DateTimeField(help_text = "date published")
	comments = ListField(ReferenceField(Comment))
	url = StringField(max_length = 100)
	votes = EmbeddedDocumentListField(Vote)
	user_id = IntField(default = 1)
	score = FloatField(default  =0)

	meta = {
		'indexes': [
			'question', 
			('pub_date', '+question')
		],
		"strict" : False
	}

	def joinTitle(self):
		'''Helper method for joining title'''
		return '-'.join([e.lower() for e in self.question.split()])

	def setURL(self):
		'''Make a url for the Question Instance'''
		pattern = '[^a-zA-Z0-9-]'
		self.url  = re.sub(pattern,'', self.joinTitle()).lower()

	@property
	def qid(self):
		return str(self.id)

	@classmethod
	def forUrl(self,url):
		'''Find a Question using url'''
		return self.objects.get(url = url)

	def serialize(self):
		'''Extending to_json() of Mongoengine'''
		data = json.loads(self.to_json())
		data["voteCount"] = self.voteCount
		return json.dumps(data)

class Messages(Document):
	'''
	Model for Messages
	'''
	sender_id = IntField(default = 1)
	receiver_id = IntField(default = 1)
	message = StringField(max_length  =1000)
	time = DateTimeField(help_text = "time sent")

	def _getUser(self,user_id):
		return User.objects.get(pk = user_id)
		
	@property
	def sender(self):
		'''Return User object of the message sender'''
		return self._getUser(self.sender_id)

	@property
	def receiver(self):
		'''Return User object of the message receiver'''
		return self._getUser(self.receiver_id)


class Favourites(Document):
	user_id = IntField(default = 1)
	kind = StringField()
	obj_id = StringField()

forums/views/Discussions.py
from django.views import generic,View
from django.http import HttpResponse, HttpResponseRedirect, Http404, JsonResponse
from forums.models import Question,Comment
from forums.Algorithms import voteCount
from .Forms import QuestionForm
from django.urls import reverse
from django.shortcuts import render,redirect
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from forums.views.Base import BaseView
import json,datetime

class Redirect(View):
	def dispatch(self,request,*args,**kwargs):
		return redirect("/discussions/")

class Index(View):
	'''
	Rendering the Forums index page
	'''
	template_name = "discussions/index.html"

	#class attribute to determine the sorting to be used
	sortMapper = {
		"" : Question.featured,
		"featured" : Question.featured,
		"latest" : Question.latest,
		"unanswered" : Question.unanswered
	}

	def dispatch(self,request,*args,**kwargs):
		_sort = self.sortMapper.get(kwargs.get("sort"))
		return render(request , self.template_name , {"question_list" : _sort()})


class Thread(generic.DetailView):
	'''
	View to manage a thread
	'''
	model = Question
	template_name = "discussions/thread.html"

	def getContext(self,request,**kwargs):
		q = Question.forUrl(kwargs.get("key"))
		if not q:
			raise Http404("Thread Does not exist")
		return q

	def get(self,request,*args,**kwargs):
		q = self.getContext(request,**kwargs)
		return render(request,self.template_name,{"question" : q , "user" : request.user})

class PostView(LoginRequiredMixin ,generic.edit.FormView):
	'''
	Saving the incoming form for adding a question
	'''
	template_name = "discussions/ask.html"
	form_class = QuestionForm

	def form_valid(self,form):
		q = Question(pub_date = datetime.datetime.now())
		for i,e in form.cleaned_data.items():
			setattr(q,i,e)
		try:
			q.setURL()
			dup = Question.forUrl(q.url)
			if dup is not None:
				return HttpResponse(status = 400)
			q.save()
		except Exception as e:
			print(e)
		else:
			return HttpResponseRedirect("/discussions/%s"%q.url)

		return super().form_valid(form)

	

class QuestionView(BaseView,SingleObjectMixin,View):
	'''
	View to manage actions on a question:
	1. Voting
	'''
	def post(self,request,*args,**kwargs):
		if request.user.id is not None:
			self.request = request
			qid,vote = self.fromRequest("qid","vote")
			v = {
				"uid" : request.user.id,
				"vote" : vote
			}
			q = Question.setVote(qid,v).serialize()
			return HttpResponse(q , content_type = "application/json")
		return HttpResponse(status  =403)

class CommentView(BaseView,SingleObjectMixin,View):
	'''
	Wrapper for managing Actions on a comment:
	1. Voting
	2. Comment on Post
	3. Reply to a comment
	'''
	objMapper = {
		"comment" : Comment,
		"question" : Question
	}

	def vote(self,request,*args,**kwargs):
		self.request = request
		uid , cid,vote = self.fromRequest("uid","cid" , "vote")
		v = {
			"uid" : uid,
			"vote" : vote 
		}
		c = Comment.setVote(cid,v).to_json()
		return HttpResponse(c, content_type = "application/json")

	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		'''
		Exempting csrf check for testing
		'''
		self.request = request
		return super().dispatch(request, *args, **kwargs)

	def post(self,request,*args,**kwargs):
		if request.user.id is not None:
			if "action" in kwargs:
				#action kwarg is passed through url. Voting is performed in this block
				#similarly more functionality can be added by defining appropriate actions-method pairs
				return getattr(self,kwargs.get("action"))(request,*args,**kwargs)

			#Adding Comment to question or Replying to Comment works through this block	
			#method kwarg is passed through url definition
			
			obj = self.objMapper.get(kwargs.get("method"))
			if request.user.id is not None:
				qid,comment = self.fromRequest("qid","comment")
				c = obj.setComment(qid,comment,request.user.id)
				return HttpResponse(c.to_json(), content_type = "application/json")
		return HttpResponse(status = 403)

forums/views/Errors.py
from django.views import View
from django.shortcuts import render

class View404(View):
	def get(self,request,*args,**kwargs):
		return render(request,"404.html")

forums/views/Forms.py
from django.views import generic
from forums.models import Question , Comment
from django import forms

class QuestionForm(forms.Form):
	'''
	Form For Posting Question
	'''
	question = forms.CharField(label = "Title" , required = True , max_length = 200)
	description = forms.CharField( label = "Description" , required = True , max_length = 1000)

forums/views/User.py
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.contrib.auth.models import User
from forums.models import Question, Comment , Messages , Favourites
from django.urls import reverse
from django.shortcuts import render , get_object_or_404
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from forums.views.Base import BaseView
import json

class UserData():
	'''
	Simple Wrapper for extending accessibility of user object inside templates 
	'''
	def __init__(self,user):
		self.user = user

	@property
	def questions(self):
		'''Return the Posts by the user'''
		return Question.objects.filter(user_id = self.user.id)
	@property
	def comments(self):
		'''Return the comments by the user'''
		return Comment.objects.filter(user_id = self.user.id)
	@property
	def username(self):
		'''Return the username'''
		return self.user.username
	@property
	def first_name(self):
		'''Return the first_name'''
		return self.user.first_name
	@property
	def last_name(self):
		'''Return the last_name'''
		return self.user.last_name
	@property
	def inbox(self):
		'''Return the messages in inbox of the user'''
		return Messages.objects.filter(receiver_id = self.id)
	@property
	def sentbox(self):
		'''Return the messages in the sentbox of the user'''
		return Messages.objects.filter(sender_id = self.id)
	@property
	def favourites(self):
		'''Returns the favourites'''
		return Favourites.objects.filter(user_id = self.id)
	@property
	def id(self):
		'''Return the id of the user'''
		return self.user.id



class ProfileView( BaseView,View):
	'''
	Wrapper for the actions directly related to the user profile like:
		1. Viewing profile page
		2. Marking Favourites
	View can only be accessed if user is logged in   
	'''
	class Mapper():
		objMapper = {
			"comment" : Comment,
			"question" : Question
		}
		'''Depending on the functionality many more classmethods can be added to extend functionality'''
		@classmethod
		def favourite(self,request,**kwargs):
			obj = self.objMapper.get(kwargs.get("method"))
			oid  = self.fromRequest("id")
			f = Favourites(kind = kwargs.get("method") , obj_id = oid , user_id = request.user.id )
			f.save()
			return HttpResponse(f.to_json() , content_type = "application/json")

	@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		'''Bypassing the csrf check'''
		self.request = request
		return super().dispatch(request, *args, **kwargs)

	def get(self,request,*args,**kwargs):
		'''Rendering the profile view'''
		user = UserData(request.user)
		return render(request , "user/profile.html" , {"user" : user } )
	
	def post(self,request,*args,**kwargs):
		if request.user.id is not None:
			return getattr(self.Mapper,kwargs.get("action"))(request,**kwargs) 
		return HttpResponse(status = 403)

class AccountView(View):
	'''
	Wrapper for account related functionalities like:
		1. Sending Message
		2. View Public Account Page
	'''
	http_method_names = ["get","post"]
	def get(self,request,*args,**kwargs):
		key = kwargs.get("username")
		user = get_object_or_404(User,username = key)
		return render(request , "user/account.html" , {"user" : UserData(user)})

	def post(self,request,*args,**kwargs):
		'''
		Manages the messaging
		'''
		if request.user.id is not None:
			sender_id = request.user.id
			receiver_id = request.POST.get("to")
			message = request.POST.get("m")
			m = Messages(sender_id = int(sender_id) , receiver_id = int(receiver_id) , message= message ).save()
			return HttpResponse(m.to_json() , content_type = "application/json")
		return HttpResponse(status = 403)


	

forums/templates/user/account.html
{% extends "../base/base.html" %}
{% block content %}
<div class="ui top attached tabular menu">
  <a class="item active" data-tab="first">Posts ({{user.questions | length }})</a>
  <a class="item" data-tab="second">Comments ({{user.comments | length }})</a>
  <a class="item" data-tab="third"><i class="fa fa-envelope-o"></i>&nbsp;Send Message</a>
</div>
<div class="ui bottom attached tab segment active" data-tab="first">
	{% if user.questions|length > 0 %}
  	{% for question in user.questions %}
			  	<div class="ui segment">
	    			<div class="ui huge header" id="topic-name"> <a href="{% url 'forums:thread' question.url %}">{{ question.question }}</a> </div>
					<div class="ui items">
						<div class="item">
							<a href="#"><span data-attr="vote" data-value="1" data-parent={{question.qid}} ><i class="fa fa-thumbs-o-up"></i></span></a>
							&nbsp;&nbsp;&nbsp;
							<a href="#"><span data-attr="vote" data-value="-1" data-parent={{question.qid}}><i class="fa fa-thumbs-o-down"></i></span></a>
							&nbsp;&nbsp;&nbsp;
							{{question.voteCount}}
							<span> &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp; </span>
							<span> <i class="fa fa-comments-o"></i>  &nbsp;&nbsp; {{quesion.comments | length }} </span>
						</div>
					</div>
	  	</div>
	{% endfor %}
	{% else %}
	<div class="ui raised very padded text container segment">
		<h2 class="ui header">Dogs Roles with Humans</h2>
		<p></p>
		<p></p>
	</div>
	{% endif %}
</div>
<div class="ui bottom attached tab segment" data-tab="second">
	<div class="ui comments">

{% if user.comments|length > 0%}
	<div class="ui comments">

	  {% for comment in user.comments %}
	    <div class="content">
	      <a class="author"><h3><a href="/discussions/{{comment.question_id.url}}">{{comment.question_id.question}}</a></h3></a>
	      <div class="metadata">
	        <!-- <span class="date">Today at 5:42PM</span> -->
	      </div>
	      <div class="text">
	        {{comment.comment_text}}
	      </div>
	    </div>
	  <hr>
	  {% endfor %}
	</div>
	{% else %}
	<div class="ui raised very padded text container segment">
		<h2 class="ui header">No Comments</h2>
		<p></p>
		<p></p>
	</div>
	{% endif %}
	</div>
</div>
<div class="ui bottom attached tab segment" data-tab="third">
	<div class="ui form">
	  <div class="field">
		<div class="ui sizer vertical segment">
			<div class="ui huge header">Message {{user.username}}</div>
			<p></p>
		</div>
	    <textarea name="message" id="text_message" ></textarea>
	  </div> 
	  <div class="ui submit button" id="send_message" data-user="{{user.id}}">Send</div>
	</div>
</div>

{% endblock %}

{% block footer %}
<script type="text/javascript">
	$('.menu .item')
	    .tab();

	 $(document).on("click","#send_message" , function(){
	 	var message = $("#text_message").val(),
	 		user =  $(this).attr("data-user");
	 	if(message.length > 0){
	 		var data = {
	 			m : message,
	 			to : user
	 		}
	 		$.post("/discussions/message",data , function(){
	 			console.log(arguments);
	 		})
	 	}else{
	 		$(this).popup({
	 			content : "Woo hoo",
	 			on:"manual",
	 			closable : true
	 		});
	 		$(this).popup("show")
	 	}
	 })
</script>
{% endblock %}

forums/templates/user/profile.html
{% extends "../base/base.html" %}
{% block content %}
<div class="ui top attached tabular menu">
  <a class="item active" data-tab="first">Posts ({{user.questions | length }})</a>
  <a class="item" data-tab="second">Comments ({{user.comments | length }})</a>
  <a class="item" data-tab="third">Inbox ({{user.inbox | length }})</a>
  <a class="item" data-tab="fourth">Sentbox ({{user.sentbox | length }})</a>
</div>
<div class="ui bottom attached tab segment active" data-tab="first">
	{% if user.questions|length > 0 %}
  	{% for question in user.questions %}
			  	<div class="ui segment">
	    			<div class="ui huge header" id="topic-name"> <a href="{% url 'forums:thread' question.url %}">{{ question.question }}</a> </div>
					<div class="ui items">
						<div class="item">
							<a href="#"><span data-attr="vote" data-value="1" data-parent={{question.qid}} ><i class="fa fa-thumbs-o-up"></i></span></a>
							&nbsp;&nbsp;&nbsp;
							<a href="#"><span data-attr="vote" data-value="-1" data-parent={{question.qid}}><i class="fa fa-thumbs-o-down"></i></span></a>
							&nbsp;&nbsp;&nbsp;
							{{question.voteCount}}
							<span> &nbsp;&nbsp;&nbsp; | &nbsp;&nbsp;&nbsp; </span>
							<span> <i class="fa fa-comments-o"></i>  &nbsp;&nbsp; {{question.comments | length }} </span>
						</div>
					</div>
	  	</div>
	{% endfor %}
	{% else %}
	<div class="ui raised very padded text container segment">
		<h2 class="ui header">No Posts</h2>
		<p></p>
		<p></p>
	</div>
	{% endif %}
</div>
<div class="ui bottom attached tab segment" data-tab="second">
	{% if user.comments|length > 0%}
	<div class="ui comments">

	  {% for comment in user.comments %}
	    <div class="comment">
	    <div class="content">
	      <a class="author"><h3><a href="/discussions/{{comment.question_id.url}}">{{comment.question_id.question}}</a></h3></a>
	      <div class="metadata">
	        <!-- <span class="date">Today at 5:42PM</span> -->
	      </div>
	      <div class="text">
	        {{comment.comment_text}}
	      </div>
	      <div class="actions">
	        <!-- <a class="reply">Reply</a> -->
	      </div>
	    </div>
	  </div>
	  <div class="ui divider"></div>
	  {% endfor %}
	</div>
	{% else %}
	<div class="ui raised very padded text container segment">
		<h2 class="ui header">No Comments</h2>
		<p></p>
		<p></p>
	</div>
	{% endif %}
</div>
<div class="ui bottom attached tab segment" data-tab="third">

	{% if user.inbox|length > 0 %}
	<div class="ui feed">
	{% for message in user.inbox %}
		<div class="event">
			<div class="label">
				<img src="/images/avatar/small/joe.jpg">
			</div>
			<div class="content">
				<div class="summary">
					<a> {{message.sender.username}} </a>
					<div class="date">
						{{message.time}}
					</div>
				</div>
				<div class="extra text">
					{{message.message}}
				</div>

			</div>
		</div>
	{% endfor  %}
	</div>
	{% else %}
	<div class="ui raised very padded text container segment">
		<h2 class="ui header">No Messages</h2>
		<p></p>
		<p></p>
	</div>
	{% endif %}
</div>
<div class="ui bottom attached tab segment" data-tab="fourth">
	{% if user.sentbox|length > 0 %}
	<div class="ui feed">
	{% for message in user.sentbox %}
		<div class="event">
			<div class="label">
				<img src="/images/avatar/small/joe.jpg">
			</div>
			<div class="content">
				<div class="summary">
					<a> {{message.receiver.username}} </a>
					<div class="date">
						{{message.time}}
					</div>
				</div>
				<div class="extra text">
					{{message.message}}
				</div>

			</div>
		</div>
	{% endfor  %}
	</div>
	{% else %}
	<div class="ui raised very padded text container segment">
		<h2 class="ui header">No Messages</h2>
		<p></p>
		<p></p>
	</div>
	{% endif %}
</div>

{% endblock %}

{% block footer %}
<script type="text/javascript">
	$('.menu .item')
	    .tab();
</script>
{% endblock %}